### ISSUE TITLE
Can you provide the mathematical equations of the Column Simulator?

### ISSUE THREAD

**Issue by xiuxinY** [dwsideriusNIST/adsorption_tools#2]
I don't know what assumptions you made about the adsorption bed. It would be quite helpful if you could provide the equations solved by this program.

**Comment by dwsideriusNIST** [comment]
As noted in the documentation, this column simulator is based on the constant-pressure, plug-flow model provided in:

> Van Assche, T.R.C., Baron, G., Denayer, J.F.M., Molecular separations with breathing metal-organic frameworks: modelling packed bed adsorbers, Dalton Trans., 2016, 45, pp. 4416-4430. (https://dx.doi.org/10.1039/C6DT00258G)
